// Sample data for the platform — Sheikh Abdulhakim's Al-Qarawiyyin Academy
window.APP_DATA = {
  instructor: {
    name: "Sheikh Abdulhakim",
    title: "Imam · Mufassir · Founder",
    initials: "ع",
    bio: "Sheikh Abdulhakim is a graduate of the Islamic University of Madinah and holds an ijazah in the recitation of Hafs 'an 'Asim. He has spent the last fifteen years teaching Qur'an, Fiqh, and the Arabic sciences to students in East Africa and the diaspora.",
    courses: 8,
    students: 4612,
    rating: 4.9,
  },

  categories: [
    { id: "all",       label: "All", count: 24 },
    { id: "quran",     label: "Qur'an", count: 8, arabic: "القرآن" },
    { id: "arabic",    label: "Arabic", count: 5, arabic: "العربية" },
    { id: "fiqh",      label: "Fiqh", count: 4, arabic: "الفقه" },
    { id: "aqeedah",   label: "Aqeedah", count: 3, arabic: "العقيدة" },
    { id: "seerah",    label: "Seerah", count: 2, arabic: "السيرة" },
    { id: "hadith",    label: "Hadith", count: 2, arabic: "الحديث" },
  ],

  // course covers — leather color + foil color + classification stamp
  courses: [
    {
      id: "tajweed-foundations",
      slug: "tajweed-foundations",
      cat: "quran",
      catLabel: "Qur'an",
      title: "Foundations of Tajwīd",
      arabic: "أساسيات التجويد",
      somali: "Aasaaska Tajwiidka",
      coverColor: "forest",
      stamp: "I",
      price: 89,
      duration: "12 weeks",
      lessons: 32,
      students: 1248,
      rating: 4.9,
      level: "Beginner",
      enrolled: true,
      progress: 0.42,
      blurb: "The rules of pronunciation that shape every recitation — taught from the first letter, with audio examples for every makhraj.",
      lede: "Begin where you are. Master the points of articulation, the qualities of the letters, and the patterns of stopping — the quiet discipline that makes recitation faithful.",
      modules: [
        { title: "The Mouth as Instrument", lessons: [
          { t: "Welcome & how this course is taught", d: "8:24", free: true, done: true },
          { t: "Niyyah — the place of intention", d: "12:08", free: true, done: true },
          { t: "The seventeen points of articulation", d: "22:14", done: true },
          { t: "Practice plate — al-Fātiḥah, slowly", d: "18:42", done: true },
        ]},
        { title: "Qualities of the Letters", lessons: [
          { t: "Sifāt that have an opposite", d: "24:11", done: true },
          { t: "Sifāt without opposite", d: "19:36", done: false, active: true },
          { t: "Hams and Jahr in practice", d: "16:02" },
          { t: "Field exercise — record yourself", d: "—" },
        ]},
        { title: "Rules of Nūn and Mīm", lessons: [
          { t: "Iẓhār", d: "14:20" },
          { t: "Idghām with and without ghunnah", d: "21:45" },
          { t: "Iqlāb", d: "11:30" },
          { t: "Ikhfā'", d: "18:15" },
        ]},
        { title: "Madd — the long vowels", lessons: [
          { t: "Natural madd", d: "13:50" },
          { t: "Connected and detached madd", d: "20:08" },
          { t: "Madd at stops", d: "16:42" },
        ]},
      ],
    },
    {
      id: "arabic-grammar-1",
      slug: "arabic-grammar-1",
      cat: "arabic",
      catLabel: "Arabic",
      title: "Classical Arabic I",
      arabic: "العربية الفصحى",
      somali: "Carabi: Qaybta Kowaad",
      coverColor: "clay",
      stamp: "II",
      price: 129,
      duration: "16 weeks",
      lessons: 48,
      students: 892,
      rating: 4.8,
      level: "Beginner",
      enrolled: true,
      progress: 0.18,
      blurb: "Nahw and sarf from first principles, taught the way the early madrasas taught — through recitation, parsing, and patient repetition.",
    },
    {
      id: "fiqh-worship",
      slug: "fiqh-worship",
      cat: "fiqh",
      catLabel: "Fiqh",
      title: "Fiqh of Worship",
      arabic: "فقه العبادات",
      somali: "Fiqhi cibaadada",
      coverColor: "umber",
      stamp: "III",
      price: 99,
      duration: "10 weeks",
      lessons: 28,
      students: 1431,
      rating: 4.9,
      level: "All levels",
      enrolled: false,
      blurb: "Wudu, prayer, fasting, zakat, hajj — the four schools compared with care, the evidences walked through, the everyday questions answered.",
    },
    {
      id: "aqeedah-tahawiyyah",
      slug: "aqeedah-tahawiyyah",
      cat: "aqeedah",
      catLabel: "Aqeedah",
      title: "Al-ʿAqīdah aṭ-Ṭaḥāwiyyah",
      arabic: "العقيدة الطحاوية",
      somali: "Caqiidada Ṭaḥaawiyyah",
      coverColor: "forest",
      stamp: "IV",
      price: 109,
      duration: "14 weeks",
      lessons: 36,
      students: 624,
      rating: 5.0,
      level: "Intermediate",
      enrolled: false,
      blurb: "A careful reading of the great primer of Sunni creed — each article unpacked, each evidence traced, each common confusion addressed.",
    },
    {
      id: "seerah-meccan",
      slug: "seerah-meccan",
      cat: "seerah",
      catLabel: "Seerah",
      title: "The Meccan Years",
      arabic: "السيرة المكية",
      somali: "Sennada Maka",
      coverColor: "gold",
      stamp: "V",
      price: 79,
      duration: "8 weeks",
      lessons: 22,
      students: 2104,
      rating: 4.9,
      level: "All levels",
      enrolled: true,
      progress: 0.78,
      blurb: "The first thirteen years of the prophetic mission, narrated with the major sources side by side — Ibn Hishām, aṭ-Ṭabarī, Ibn Kathīr.",
    },
    {
      id: "hadith-nawawi",
      slug: "hadith-nawawi",
      cat: "hadith",
      catLabel: "Hadith",
      title: "Forty Hadith of an-Nawawī",
      arabic: "الأربعون النووية",
      somali: "Afartanka Xadiis ee an-Nawawiyya",
      coverColor: "slate",
      stamp: "VI",
      price: 69,
      duration: "10 weeks",
      lessons: 40,
      students: 3210,
      rating: 4.9,
      level: "All levels",
      enrolled: false,
      blurb: "Forty narrations the scholars considered the pillars of the religion. We read each in Arabic, parse the chain, and sit with the meaning.",
    },
    {
      id: "tafsir-juz-amma",
      slug: "tafsir-juz-amma",
      cat: "quran",
      catLabel: "Qur'an",
      title: "Tafsīr of Juz' ʿAmma",
      arabic: "تفسير جزء عمّ",
      somali: "Tafsiir Juzʼ Camma",
      coverColor: "umber",
      stamp: "VII",
      price: 89,
      duration: "12 weeks",
      lessons: 30,
      students: 1876,
      rating: 4.8,
      level: "All levels",
      enrolled: false,
      blurb: "The thirtieth juzʼ — the surahs most often recited in prayer — explained verse by verse, with attention to language and context.",
    },
    {
      id: "quran-arabic-listener",
      slug: "quran-arabic-listener",
      cat: "arabic",
      catLabel: "Arabic",
      title: "Qur'anic Arabic for the Listener",
      arabic: "عربية القرآن للمستمع",
      somali: "Carabi Qur'aanka",
      coverColor: "clay",
      stamp: "VIII",
      price: 119,
      duration: "14 weeks",
      lessons: 42,
      students: 754,
      rating: 4.7,
      level: "Beginner",
      enrolled: false,
      blurb: "Enough grammar and vocabulary to follow a recitation without translation — built around the most-recited surahs.",
    },
  ],

  testimonials: [
    {
      body: "I had tried three apps before this. None of them slowed down enough to teach the makhraj. Sheikh Abdulhakim begins at the beginning and assumes nothing — by the second week my recitation had already changed.",
      name: "Amina Hassan",
      title: "Student, Toronto · Tajwīd Foundations",
      initial: "A",
    },
    {
      body: "The Arabic grammar course is taught the old way — recite the chapter, parse every word, then move on. It is harder than the gamified ones and it actually works.",
      name: "Yusuf Diallo",
      title: "Imam, Dakar · Classical Arabic",
      initial: "Y",
    },
    {
      body: "Wuxuu si tartiib ah u baraa, taas ayaa anigu raadinayey. Sheikh-ga waxa uu ku adkeeyaa fahanka inta ka horraysa qiraadda — waana sida diinta loo bartay weligeed.",
      name: "Khadija Mohamed",
      title: "Mother of four, Minneapolis · Seerah",
      initial: "K",
    },
  ],

  values: [
    {
      icon: "book",
      title: "Taught by an ijazah-holder",
      body: "Every course is taught by Sheikh Abdulhakim himself — graduate of the Islamic University of Madinah, with full chains of transmission in recitation.",
    },
    {
      icon: "lamp",
      title: "Madrasa rhythm, modern format",
      body: "Short lessons, daily-recitation prompts, and patient repetition — the cadence of a traditional seminary, on your phone or your desk.",
    },
    {
      icon: "globe",
      title: "Arabic · English · Somali",
      body: "Lessons are taught in plain English, with Arabic source-text on every screen and Somali translations for the core terminology.",
    },
    {
      icon: "ribbon",
      title: "Ijazah upon completion",
      body: "Students who complete a course and pass the oral examination receive a written ijazah signed by the Sheikh.",
    },
  ],

  recentEnrollments: [
    { id: "ENR-04891", name: "Layla Abdullahi",  course: "Foundations of Tajwīd",   date: "12 May 2026", amount: 89 },
    { id: "ENR-04890", name: "Mohammed Sayed",   course: "Fiqh of Worship",        date: "12 May 2026", amount: 99 },
    { id: "ENR-04889", name: "Ibrahim Touré",    course: "The Meccan Years",       date: "11 May 2026", amount: 79 },
    { id: "ENR-04888", name: "Hawa Jamal",       course: "Classical Arabic I",     date: "11 May 2026", amount: 129 },
    { id: "ENR-04887", name: "Omar Karim",       course: "Forty Hadith of an-Nawawī", date: "10 May 2026", amount: 69 },
    { id: "ENR-04886", name: "Sumaya Yusuf",     course: "Foundations of Tajwīd",  date: "10 May 2026", amount: 89 },
    { id: "ENR-04885", name: "Khalid Ahmed",     course: "Tafsīr of Juz' ʿAmma",  date: "09 May 2026", amount: 89 },
  ],
};
